language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v[0-9\.]+$/

php:
  - 5.3
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install v4.4.2
  - node --version
  - npm install && npm start
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - ./vendor/bin/phpunit
