language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+$/"
php:
  - 5.6
  - 7.0
  - 7.2
  - 7.4
services:
  - mysql
env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/never-let-me-go/
    - secure: "HM/WQwdBmnmvHJ+60V7zwHEa1kpcLY0vHzWMJWhJwA89JjIm+YFJL1XRZUxgooVKK/L0zBSMxrmy7oG2KtqGIcoXH2NYnbrQHUblbw9xIejfkowBC4QMcCXmYlVUmR1zc42XUFzn7Dd8YkGyqoSHYa4AvQrLu35b4yt8m6L5JP0="
before_script:
  - composer install
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.0/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install v10.13.0
  - node --version
  - npm install && npm start
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
  - composer test
before_deploy:
  - export WP_PULUGIN_DEPLOY=1
deploy:
  - provider: script
    script: curl -L https://raw.githubusercontent.com/fumikito/travis2wpplugin/master/deploy.sh | bash
    on:
      php: 5.6
      tags: true
      condition: $WP_VERSION = latest
